<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.openmrs.module</groupId>
        <artifactId>emrapi</artifactId>
        <version>3.5.1-sihsalus.2</version>
    </parent>
    <artifactId>emrapi-queue-compatibility</artifactId>
    <name>EMR API and Queue integration tests</name>
    <properties>
        <main.basedir>${project.parent.basedir}</main.basedir>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>emrapi-api</artifactId>
            <version>${project.parent.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>emrapi-api</artifactId>
            <version>${project.parent.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>queue-api</artifactId>
            <version>3.1.0-sihsalus.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <testResources>
            <testResource>
                <directory>${project.basedir}/../api/src/test/resources</directory>
                <includes>
                    <include>TestingApplicationContext.xml</include>
                    <include>test-hibernate.cfg.xml</include>
                </includes>
            </testResource>
        </testResources>
    </build>
</project>
